version: "3"
services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo-s3.yaml:/etc/tempo.yaml
      - ./tempo/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"      # jaeger
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "3200:3200"  # tempo
  grafana:
    image: grafana/grafana:10.1.1
    volumes:
      - ./tempo/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
  zk:
    image: zookeeper
    ports:
      - 2181:2181
  mysql:
    image: mysql:5.6
    command: --character-set-server=utf8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dalong
      - MYSQL_USER=boss
      - MYSQL_DATABASE=boss
      - MYSQL_PASSWORD=dalong
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "19001:19001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address :19001 --quiet /data
  dremio_coordinator:
    build: .
    hostname: dremio-coordinator
    container_name: dremio-coordinator
    privileged: true
    cap_add:
      - ALL
    volumes:
      - ./conf/dremio_coor.conf:/opt/dremio/conf/dremio.conf
      - ./datas:/myappdemo
      - ./data:/opt/dremio/data
    ports:
      - "9047:9047"
      - "31010:31010"
      - "9090:9090"
      - "32010:32010"
  # dremio_coordinator-2:
  #   build: .
  #   hostname: dremio-coordinator2
  #   container_name: dremio-coordinator2
  #   volumes:
  #     - ./conf/dremio_coor2.conf:/opt/dremio/conf/dremio.conf
  #     - ./datas:/myappdemo
  #     - ./data:/opt/dremio/data
  #   ports:
  #     - "9057:9047"
  #     - "31020:31010"
  #     - "9100:9090"
  dremio_executor_1:
    build: .
    hostname: dremio-executor-1
    container_name: dremio-executor-1
    privileged: true
    cap_add:
      - ALL
    volumes:
      - ./conf/dremio_exec.conf:/opt/dremio/conf/dremio.conf
      - ./dremio-telemetry-exec.yaml:/opt/dremio/conf/dremio-telemetry.yaml
      - ./datas:/myappdemo
    ports:
      - "9048:9047"
      - "31011:31010"
      - "9091:9090"
  dremio_executor_2:
    build: .
    hostname: dremio-executor-2
    container_name: dremio-executor-2
    volumes:
      - ./conf/dremio_exec.conf:/opt/dremio/conf/dremio.conf
      - ./dremio-telemetry-exec.yaml:/opt/dremio/conf/dremio-telemetry.yaml
      - ./datas:/myappdemo
  pg:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dalongdemo
  nessie:
    image: projectnessie/nessie:0.75.0-java
    environment:
      - NESSIE_VERSION_STORE_TYPE=JDBC
      - QUARKUS.DATASOURCE.USERNAME=postgres
      - QUARKUS.DATASOURCE.PASSWORD=dalongdemo
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://pg:5432/postgres
    ports:
      - "19120:19120"
      - "19121:19121"
